### ISSUE TITLE
Form isn't valid with filled values in inputs

### ISSUE THREAD

**Issue by CyrilKrylatov** [lordfpx/AB-formValidation#9]
I have this form that has `value` attributes on its inputs elements and they are not empty.

I think the plugin should try to validate them.

I forked your codepen here https://codepen.io/CyrilKrylatov/pen/PBXoWp?editors=1000 so you can see what I'm talking about.

I tried to look in the code and change it by myself, but, you know, not my cup of tea.

**Comment by lordfpx** [comment]
Fixed
